# Here's an updated Kubernetes Deployment YAML file that includes:
# A volume (emptyDir),
# Environment variables,
# Resource limits/requests,
# And sets up an nginx container.\
#kubectl exec -it nginx-deployment-78f959d8d4-mpzj6 -- /bin/bash
#echo "<h1>Hello Kubernetes</h1>" > /usr/share/nginx/html/index.html
#kubectl port-forward nginx-deployment-78f959d8d4-mpzj6 8080:80


apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2  # Number of pod replicas
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          value: production
        - name: APP_VERSION
          value: "1.0"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      
